name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: clean
      run: make clean

    - name: raw
      run: make raw
    
    - name: Create Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: converted-files
        path: test
